version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2023.1
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host