- hosts: homeassistant
  become: true

  vars:
    pkgstoinstall: [libffi-dev, libssl-dev, python3, python3-pip]

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    # System
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: ["git", "tmux", "ufw"]

    - name: Disallow password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present

    - name: Restart ssh daemon
      service:
        name: sshd
        state: restarted

    # UFW Setup
    - name: UFW - Allow SSH connections
      ufw:
        rule: allow
        name: OpenSSH

    - name: UFW - Deny all other incoming traffic by default
      ufw:
        state: enabled
        policy: deny
        direction: incoming

    # Docker
    - name: Install a list of packages
      apt:
        name: "{{ pkgstoinstall }}"
        update_cache: yes

    - name: Remove python-configparser package
      apt:
        name: python-configparser
        state: absent

    - name: get docker convenience script
      get_url:
        url: https://get.docker.com
        dest: /home/pi/get-docker.sh

    - name: install docker
      shell: sh /home/pi/get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: make pi user execute docker commands
      shell: usermod -aG docker pi

    - name: install docker-compose
      shell: pip3 -v install docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    # # ENV file
    # - name: "Create env directory"
    #   file:
    #     path: /flodesapp/env
    #     state: directory
    # - name: Copy .env file
    #   copy:
    #     src: ../../.env.prod
    #     dest: /flodesapp/env/.env.prod
